In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\MYPC\Downloads\datasets\ambient household deaths.csv")

In [4]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,32390,32391,32392,32393,32394,32395,32396,32397,32398,32399
IndicatorCode,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,...,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA,SDGAIRBODA
Indicator,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...,Ambient and household air pollution attributab...
ValueType,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,...,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric,numeric
ParentLocationCode,AMR,AMR,AMR,AMR,AMR,AFR,AFR,AFR,AFR,EUR,...,AFR,EUR,WPR,AFR,AFR,AMR,EUR,AFR,EMR,AFR
ParentLocation,Americas,Americas,Americas,Americas,Americas,Africa,Africa,Africa,Africa,Europe,...,Africa,Europe,Western Pacific,Africa,Africa,Americas,Europe,Africa,Eastern Mediterranean,Africa
Location type,Country,Country,Country,Country,Country,Country,Country,Country,Country,Country,...,Country,Country,Country,Country,Country,Country,Country,Country,Country,Country
SpatialDimValueCode,ATG,ATG,BHS,BHS,BHS,BWA,COM,COM,COM,EST,...,MWI,KAZ,VUT,SWZ,BFA,BOL,KAZ,GIN,PAK,SLE
Location,Antigua and Barbuda,Antigua and Barbuda,Bahamas,Bahamas,Bahamas,Botswana,Comoros,Comoros,Comoros,Estonia,...,Malawi,Kazakhstan,Vanuatu,Eswatini,Burkina Faso,Bolivia (Plurinational State of),Kazakhstan,Guinea,Pakistan,Sierra Leone
Period type,Year,Year,Year,Year,Year,Year,Year,Year,Year,Year,...,Year,Year,Year,Year,Year,Year,Year,Year,Year,Year
Period,2019,2019,2019,2019,2019,2019,2019,2019,2019,2019,...,2010,2010,2010,2010,2010,2010,2010,2010,2010,2010
IsLatestYear,True,True,True,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
Dim1 type,Sex,Sex,Sex,Sex,Sex,Sex,Sex,Sex,Sex,Sex,...,Sex,Sex,Sex,Sex,Sex,Sex,Sex,Sex,Sex,Sex
Dim1,Both sexes,Female,Both sexes,Female,Male,Female,Both sexes,Female,Male,Female,...,Male,Male,Female,Male,Male,Male,Female,Female,Both sexes,Female
Dim1ValueCode,SEX_BTSX,SEX_FMLE,SEX_BTSX,SEX_FMLE,SEX_MLE,SEX_FMLE,SEX_BTSX,SEX_FMLE,SEX_MLE,SEX_FMLE,...,SEX_MLE,SEX_MLE,SEX_FMLE,SEX_MLE,SEX_MLE,SEX_MLE,SEX_FMLE,SEX_FMLE,SEX_BTSX,SEX_FMLE
Dim2 type,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,...,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes,GHE cause of death codes
Dim2,"Trachea, bronchus, lung cancers","Trachea, bronchus, lung cancers","Trachea, bronchus, lung cancers","Trachea, bronchus, lung cancers","Trachea, bronchus, lung cancers","Trachea, bronchus, lung cancers","Trachea, bronchus, lung cancers","Trachea, bronchus, lung cancers","Trachea, bronchus, lung cancers","Trachea, bronchus, lung cancers",...,Acute lower respiratory infections,Ischaemic heart disease,Ischaemic heart disease,Ischaemic heart disease,Ischaemic heart disease,All causes,All causes,Acute lower respiratory infections,Ischaemic heart disease,Acute lower respiratory infections
Dim2ValueCode,GHECAUSE_GHE000680,GHECAUSE_GHE000680,GHECAUSE_GHE000680,GHECAUSE_GHE000680,GHECAUSE_GHE000680,GHECAUSE_GHE000680,GHECAUSE_GHE000680,GHECAUSE_GHE000680,GHECAUSE_GHE000680,GHECAUSE_GHE000680,...,GHECAUSE_GHE000390,GHECAUSE_GHE001130,GHECAUSE_GHE001130,GHECAUSE_GHE001130,GHECAUSE_GHE001130,GHECAUSE_GHE000000,GHECAUSE_GHE000000,GHECAUSE_GHE000390,GHECAUSE_GHE001130,GHECAUSE_GHE000390
Dim3 type,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dim3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dim3ValueCode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DataSourceDimValueCode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DataSource,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FactValueNumericPrefix,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FactValueNumeric,0.19,0.084,0.079,0.042,0.13,0.33,0.11,0.0,0.23,0.19,...,95.69,97.01,97.23,96.93,97.25,96.72,97.77,98.22,99.23,98.81
FactValueUoM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FactValueNumericLowPrefix,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FactValueNumericLow,0.056,0.024,0.0,0.0,0.0,0.22,0.093,0.0,0.19,0.072,...,80.7,62.52,70.28,73.26,76.51,78.31,66.12,83.73,76.94,83.39
FactValueNumericHighPrefix,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FactValueNumericHigh,0.41,0.18,0.24,0.13,0.39,0.43,0.13,0.0,0.27,0.37,...,110.6,135.6,121.6,120.5,114.7,117.9,136.9,110.7,119.7,111.7
Value,0 [0-0],0 [0-0],0 [0-0],0 [0-0],0 [0-0],0 [0-0],0 [0-0],0 [0-0],0 [0-0],0 [0-0],...,96 [81-111],97 [63-136],97 [70-122],97 [73-120],97 [77-115],97 [78-118],98 [66-137],98 [84-111],99 [77-120],99 [83-112]
FactValueTranslationID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FactComments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Language,EN,EN,EN,EN,EN,EN,EN,EN,EN,EN,...,EN,EN,EN,EN,EN,EN,EN,EN,EN,EN
DateModified,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,...,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z,2024-10-02T18:30:00.000Z

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32400 entries, 0 to 32399
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   IndicatorCode               32400 non-null  object
 1   Indicator                   32400 non-null  object
 2   ValueType                   32400 non-null  object
 3   ParentLocationCode          32400 non-null  object
 4   ParentLocation              32400 non-null  object
 5   Location type               32400 non-null  object
 6   SpatialDimValueCode         32400 non-null  object
 7   Location                    32400 non-null  object
 8   Period type                 32400 non-null  object
 9   Period                      32400 non-null  int64
 10  IsLatestYear                32400 non-null  bool
 11  Dim1 type                   32400 non-null  object
 12  Dim1                        32400 non-null  object
 13  Dim1ValueCode               32400 non-null  object
 14  Dim2 type                   32400 non-null  object
 15  Dim2                        32400 non-null  object
 16  Dim2ValueCode               32400 non-null  object
 17  Dim3 type                   0 non-null      float64
 18  Dim3                        0 non-null      float64
 19  Dim3ValueCode               0 non-null      float64
 20  DataSourceDimValueCode      0 non-null      float64
 21  DataSource                  0 non-null      float64
 22  FactValueNumericPrefix      0 non-null      float64
 23  FactValueNumeric            32400 non-null  float64
 24  FactValueUoM                0 non-null      float64
 25  FactValueNumericLowPrefix   0 non-null      float64
 26  FactValueNumericLow         32400 non-null  float64
 27  FactValueNumericHighPrefix  0 non-null      float64
 28  FactValueNumericHigh        32400 non-null  float64
 29  Value                       32400 non-null  object
 30  FactValueTranslationID      0 non-null      float64
 31  FactComments                0 non-null      float64
 32  Language                    32400 non-null  object
 33  DateModified                32400 non-null  object
dtypes: bool(1), float64(14), int64(1), object(18)
memory usage: 8.2+ MB

In [6]:
df.columns = df.columns.str.lower().str.strip()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32400 entries, 0 to 32399
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   indicatorcode               32400 non-null  object
 1   indicator                   32400 non-null  object
 2   valuetype                   32400 non-null  object
 3   parentlocationcode          32400 non-null  object
 4   parentlocation              32400 non-null  object
 5   location type               32400 non-null  object
 6   spatialdimvaluecode         32400 non-null  object
 7   location                    32400 non-null  object
 8   period type                 32400 non-null  object
 9   period                      32400 non-null  int64
 10  islatestyear                32400 non-null  bool
 11  dim1 type                   32400 non-null  object
 12  dim1                        32400 non-null  object
 13  dim1valuecode               32400 non-null  object
 14  dim2 type                   32400 non-null  object
 15  dim2                        32400 non-null  object
 16  dim2valuecode               32400 non-null  object
 17  dim3 type                   0 non-null      float64
 18  dim3                        0 non-null      float64
 19  dim3valuecode               0 non-null      float64
 20  datasourcedimvaluecode      0 non-null      float64
 21  datasource                  0 non-null      float64
 22  factvaluenumericprefix      0 non-null      float64
 23  factvaluenumeric            32400 non-null  float64
 24  factvalueuom                0 non-null      float64
 25  factvaluenumericlowprefix   0 non-null      float64
 26  factvaluenumericlow         32400 non-null  float64
 27  factvaluenumerichighprefix  0 non-null      float64
 28  factvaluenumerichigh        32400 non-null  float64
 29  value                       32400 non-null  object
 30  factvaluetranslationid      0 non-null      float64
 31  factcomments                0 non-null      float64
 32  language                    32400 non-null  object
 33  datemodified                32400 non-null  object
dtypes: bool(1), float64(14), int64(1), object(18)
memory usage: 8.2+ MB

In [8]:
df = df.drop(columns = ['indicatorcode', 'valuetype', 'parentlocationcode', 'spatialdimvaluecode', 'period type', 'islatestyear', 'dim1valuecode', 'dim3 type', 'dim3', 'dim3valuecode', 'datasourcedimvaluecode', 'datasource', 'factvaluenumericprefix', 'factvalueuom', 'factvaluenumericlowprefix', 'factvaluenumerichighprefix', 'value', 'factvaluetranslationid', 'factcomments', 'language', 'datemodified'])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32400 entries, 0 to 32399
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   indicator             32400 non-null  object
 1   parentlocation        32400 non-null  object
 2   location type         32400 non-null  object
 3   location              32400 non-null  object
 4   period                32400 non-null  int64
 5   dim1 type             32400 non-null  object
 6   dim1                  32400 non-null  object
 7   dim2 type             32400 non-null  object
 8   dim2                  32400 non-null  object
 9   dim2valuecode         32400 non-null  object
 10  factvaluenumeric      32400 non-null  float64
 11  factvaluenumericlow   32400 non-null  float64
 12  factvaluenumerichigh  32400 non-null  float64
dtypes: float64(3), int64(1), object(9)
memory usage: 3.2+ MB

In [10]:
df.head()

,indicator,parentlocation,location type,location,period,dim1 type,dim1,dim2 type,dim2,dim2valuecode,factvaluenumeric,factvaluenumericlow,factvaluenumerichigh
0,Ambient and household air pollution attributab...,Americas,Country,Antigua and Barbuda,2019,Sex,Both sexes,GHE cause of death codes,"Trachea, bronchus, lung cancers",GHECAUSE_GHE000680,0.190,0.056,0.41
1,Ambient and household air pollution attributab...,Americas,Country,Antigua and Barbuda,2019,Sex,Female,GHE cause of death codes,"Trachea, bronchus, lung cancers",GHECAUSE_GHE000680,0.084,0.024,0.18
2,Ambient and household air pollution attributab...,Americas,Country,Bahamas,2019,Sex,Both sexes,GHE cause of death codes,"Trachea, bronchus, lung cancers",GHECAUSE_GHE000680,0.079,0.000,0.24
3,Ambient and household air pollution attributab...,Americas,Country,Bahamas,2019,Sex,Female,GHE cause of death codes,"Trachea, bronchus, lung cancers",GHECAUSE_GHE000680,0.042,0.000,0.13
4,Ambient and household air pollution attributab...,Americas,Country,Bahamas,2019,Sex,Male,GHE cause of death codes,"Trachea, bronchus, lung cancers",GHECAUSE_GHE000680,0.130,0.000,0.39

In [11]:
df['period'].unique()

array([2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010])

In [12]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
period,32400.0,2014.500000,2.872326,2010.0,2012.00,2014.50,2017.0000,2019.0
factvaluenumeric,32400.0,37.607877,55.696171,0.0,3.12,14.16,50.5525,430.6
factvaluenumericlow,32400.0,27.825483,45.876458,0.0,1.51,8.59,34.9600,363.8
factvaluenumerichigh,32400.0,48.093617,66.269773,0.0,5.30,20.28,66.0000,503.4

In [15]:
df.to_csv("cleaned_ambient_household_deaths.csv", index = False)